config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }

    devise_scope :user do
      get 'performance', to: 'users/registrations#performance'
      post 'performance', to: 'users/registrations#performance'
      get 'done', to: 'users/registrations#done'
      post 'done', to: 'users/registrations#done'
      get 'edit_user', to: 'users/registrations#edit_user'
      post 'edit_user', to: 'users/registrations#edit_user'
      get 'update_user', to: 'users/registrations#update_user'
      put 'update_user', to: 'users/registrations#update_user'
      get 'logout', to: "users#logout"
    end

    root to: "matters#index"

    resources :users do
      resources :offers, only: [:index, :create, :destroy]
      resources :offered_lists, only: [:index] do
        put 'already_confirmed', to: 'offered_lists#already_confirmed'
        put 'unconfirm', to: 'offered_lists#unconfirm'
      end
    end

    resources :mypages, except: [:destroy]
    resources :applications_lists, only: [:index]
    resources :likes, only: [:index]
    resources :user_chatslists, only: [:index]
    resources :musician_chatslists, only: [:index]

    resources :musicians, except: [:destroy] do
      resources :musician_matterslists, only: [:index]
      resources :tags, only: [:index] do
        collection do
          get 'user_search'
        end
      end
    end


    resources :matters, only: [:new, :create, :show, :edit, :update] do
      resources :likes, only: [:create, :destroy]
      resources :applications, only: [:create, :destroy] do
        resources :applied_users, only: [:index]
      end
      resources :chats, only: [:create] do
        resources :messages, except: [:show] do
          put 'already_read', to: 'messages#already_read'
          put 'unread', to: 'messages#unread'
        end
        resources :reply_messages, except: [:show] do
          put 'already_read', to: 'reply_messages#already_read'
          put 'unread', to: 'reply_messages#unread'
        end
      end
      collection do
        get 'search'
        get 'category_search'
      end
    end



end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :matter
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :musician
  belongs_to :user
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  belongs_to :matter
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :matter
end

app/models/matter.rb
class Matter < ApplicationRecord
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :applications
  has_many :offers
  has_many :chats
  belongs_to :musician
  belongs_to :matter_category

  enum status: {
    公開:0,非公開:1
  }, _prefix: true

  enum prefecture: {
    指定なし:0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
    その他:99
  }, _prefix: true


  def self.search(search)
    if search
      Matter.joins(:musician).where(['title LIKE ? OR content LIKE ? OR name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Matter.all
    end
  end
end

app/models/matter_category.rb
class MatterCategory < ApplicationRecord
  has_many :matters
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/musician.rb
class Musician < ApplicationRecord
  validates :name, :biography, :activity_history, :activity_place, :email ,presence: true
  validates :user_id, uniqueness: true
  has_many :matters
  has_many :chats
  has_many :messages
  belongs_to :user
  has_one :block
  mount_uploader :image, ImageUploader
  # mount_uploader :sound_source, AudioFileUploader
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :user_id, uniqueness: { scope: :matter_id }
  belongs_to :user
  belongs_to :matter
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :users, through: :tags
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  def self.search(search)
    if search
      Tag.where(['skill_id LIKE ?', "%#{search}%"])
    else
      Tag.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, :name_kana, :tel, :birthday, :status ,presence: true
         validates :tel, uniqueness: true
         has_many :likes
         has_many :liked_matters, through: :likes, source: :matter
         has_many :applications
         has_many :offers
         has_many :chats
         has_many :messages
         has_many :tags
         has_many :skills, through: :tags
         has_one :block
         has_one :musician


  enum status: {
    公開:0,非公開:1
  }, _prefix: true

  enum prefecture: {
    指定なし:0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
    その他:99
  }, _prefix: true

  def already_applied?(matter)
    self.applications.exists?(matter_id: matter.id)
  end

  def already_liked?(matter)
    self.likes.exists?(matter_id: matter.id)
  end

end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :set_matter, only: [:edit, :show]
  before_action :set_deadline, only: [:index, :show, :search, :category_search]
  before_action :set_musician_user_id, only: [:index, :show, :search, :category_search]

  PER = 5

  def index
    @matters = Matter.page(params[:page]).per(PER).order("created_at DESC")
    @release_matters = @matters.where.not(status: 1)
    @accepting_matters = @release_matters.where("deadline > ?", @deadline)
  end

  def new
    @matter = Matter.new
    @musician_user_id = Musician.find_by(user_id: current_user)
  end

  def create
    @matter = Matter.new(matter_params)
    @matter.save!
    @musician_user_id = Musician.find_by(user_id: current_user)
  end

  def show
    @musician_user_id = Musician.find_by(user_id: current_user)
    @chat_user_id = Chat.find_by(matter_id: @matter, user_id: current_user)
    if user_signed_in?
      @chat = Chat.find_by(matter_id: @matter.id, user_id: current_user.id)
    end
  end

  def edit
    @musician_user_id = Musician.find_by(user_id: current_user)
  end

  def update
    @matter_edit = Matter.find_by(id: params[:id])
    @matter_edit.update(matter_params)
  end


  def search
    @matter_searchs = Matter.search(params[:search_word]).order("created_at DESC")
  end

  def category_search
    @matter_category_searchs = Matter.where(matter_category_id: params[:matter_category_id]).order("created_at DESC")
  end

  private
  def matter_params
    params.require(:matter).permit(:title, :reward, :deadline, :prefecture, :start, :end, :content, :payment, :supplement, :status, :matter_category_id).merge(musician_id: current_user.musician.id)
  end

  def set_matter
    @matter = Matter.find(params[:id])
  end

  def set_deadline
    @deadline = Time.zone.now - 1.days
  end

  def set_musician_user_id
    @musician_user_id = Musician.find_by(user_id: current_user)
  end

end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/matters/_footer.html.haml
.footer

  .footer__lower
    .footer__lower__logo
      = link_to root_path do
        = image_tag "mw_logo.png", alt: "Music Works logo", class: 'mw-logo'
    .footer__lower__copyright
      &copy; MusicWorks all rights reserved.

app/views/matters/_header.html.haml
.header

  .header__logo
    = link_to root_path do
      = image_tag "mw_logo.png", alt: "Music Works logo", class: 'mw-logo'


  .header__regist
    - if user_signed_in?
      .header__regist--user-name
        こんにちは
        = current_user.name
        様
      .header__regist--logout
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: ''

    - else
      %ul.header__regist__not-loggedin
        %li.header__regist__not-loggedin--new-regist
          = link_to "新規会員登録", '/users/sign_up'
        %li.header__regist__not-loggedin--login
          = link_to "ログイン", '/users/sign_in'

  - if user_signed_in?
    .header__upper-link
      .header__upper-link__mypage
        = link_to "会員マイページ", mypages_path, method: :get
        %br
      .header__upper-link__artist-page
        - if @musician_user_id.present?
          .header__upper-link__artist-page--already-exists
            = link_to "アーティストページ", "/musicians/#{current_user.musician.id}", method: :get
          %br
        - else
          .header__upper-link__artist-page--new-create
            = link_to "アーティストプロフィールを作成", new_musician_path
      .header__upper-link__icon
        = icon('far', 'far fa-hand-point-left')
      .header__upper-link__attention
        案件の依頼はアーティストページから作成いただけます。

app/views/matters/_matters_list.html.haml
.matters-list
  %ul
    - @accepting_matters.each do |matter|
      %li.matters-list__content

        .matters-list__content__left
          .matters-list__content__left__title
            = link_to "#{matter.title}", "/matters/#{matter.id}", method: :get, target: blank?
            .matters-list__content__left__title__category
              = icon('fas', 'fas fa-folder')
              = matter.matter_category.name

        .matters-list__content__right
          .matters-list__content__right__upper
            %p
              = icon('fas', 'fas fa-clock')
              応募受付：
            .matters-list__content__right__upper__deadline
              = matter.deadline.strftime("%Y年%m月%d日")
            %p
              まで
          .matters-list__content__right__bottom-line


          .matters-list__content__right__middle
            .matters-list__content__right__middle__reward
              = icon('fas', 'fas fa-yen-sign')
              = matter.reward
            .matters-list__content__right__middle__prefecture
              = icon('fas', 'fas fa-map-marker-alt')
              就業地域：
              = matter.prefecture
          .matters-list__content__right__middle__bottom-line


          .matters-list__content__right__lower
            - if matter.start.present?
              .matters-list__content__right__lower__start
                = icon('far', 'far fa-calendar-alt')
                業務開始予定：
                = matter.start.strftime("%Y年%m月%d日")
                〜
            .matters-list__content__right__lower__end
              = icon('far', 'far fa-calendar-alt')
              業務終了予定(希望納期)：
              = matter.end.strftime("%Y年%m月%d日")
            .matters-list__content__right__lower__bottom-line
            .matters-list__content__right__lower__musician-name
              = icon('fas', 'fas fa-user-alt')
              = link_to "#{matter.musician.name}", "/musicians/#{matter.musician.id}", target: blank?
      %br

  .top-page__matters-list__paginate
    = paginate @matters

app/views/matters/_search.html.haml
.search

  .search__keyword
    .search__keyword__title
      = icon('fas', 'fas fa-search')
      キーワードで検索
    .search__keyword__form
      = form_with(url: search_matters_path, local: true, method: :get, class: "search-form") do |f|
        = f.text_field :search_word, autocomplete: "content", placeholder: "キーワードを入力してください" ,class: 'search-input'
        %br
        = f.submit "検索" ,class: 'submit-button'

  .search__category
    .search__category__title
      = icon('fas', 'fas fa-search')
      案件カテゴリで検索
    .search__category__form
      = form_with(url: category_search_matters_path, local: true, method: :get, class: "search-form") do |f|
        = f.collection_select :matter_category_id, MatterCategory.all, :id, :name, prompt: "カテゴリを選択してください" ,class: 'search-input'
        %br
        = f.submit "検索" ,class: 'submit-button'

app/views/matters/_search_box.html.haml
.search-box

  .search-box__keyword
    .search-box__keyword__title
      = icon('fas', 'fas fa-search')
      キーワードで検索
    .search-box__keyword__form
      = form_with(url: search_matters_path, local: true, method: :get, class: "search-form") do |f|
        = f.text_field :search_word, autocomplete: "content", placeholder: "キーワードを入力してください" ,class: 'search-input'
        %br
        = f.submit "検索" ,class: 'submit-button'

  .search-box__category
    .search-box__category__title
      = icon('fas', 'fas fa-search')
      案件カテゴリで検索
    .search-box__category__form
      = form_with(url: category_search_matters_path, local: true, method: :get, class: "search-form") do |f|
        = f.collection_select :matter_category_id, MatterCategory.all, :id, :name, prompt: "カテゴリを選択してください" ,class: 'search-input'
        %br
        = f.submit "検索" ,class: 'submit-button'

app/views/matters/category_search.html.haml
.search-page
  = render 'header'

  .breadcrumb
    - breadcrumb :category_search_matters
    = breadcrumbs separator: " &rsaquo; "
  %br

  .search-page__search-box
    = render 'search_box'


  .search-page__matters-list
    %ul
      - @matter_category_searchs.each do |matter|
        - if matter.deadline > @deadline
          %li.matters-list__content

            .matters-list__content__left
              .matters-list__content__left__title
                = link_to "#{matter.title}", "/matters/#{matter.id}", method: :get, target: blank?
                .matters-list__content__left__title__category
                  = icon('fas', 'fas fa-folder')
                  = matter.matter_category.name

            .matters-list__content__right
              .matters-list__content__right__upper
                %p
                  = icon('fas', 'fas fa-clock')
                  応募受付：
                .matters-list__content__right__upper__deadline
                  = matter.deadline.strftime("%Y年%m月%d日")
                %p
                  まで
              .matters-list__content__right__bottom-line


              .matters-list__content__right__middle
                .matters-list__content__right__middle__reward
                  = icon('fas', 'fas fa-yen-sign')
                  = matter.reward
                .matters-list__content__right__middle__prefecture
                  = icon('fas', 'fas fa-map-marker-alt')
                  就業地域：
                  = matter.prefecture
              .matters-list__content__right__middle__bottom-line


              .matters-list__content__right__lower
                - if matter.start.present?
                  .matters-list__content__right__lower__start
                    = icon('far', 'far fa-calendar-alt')
                    業務開始予定：
                    = matter.start.strftime("%Y年%m月%d日")
                    〜
                .matters-list__content__right__lower__end
                  = icon('far', 'far fa-calendar-alt')
                  業務終了予定(希望納期)：
                  = matter.end.strftime("%Y年%m月%d日")
                .matters-list__content__right__lower__bottom-line
                .matters-list__content__right__lower__musician-name
                  = icon('fas', 'fas fa-user-alt')
                  = link_to "#{matter.musician.name}", "/musicians/#{matter.musician.id}", target: blank?
          %br

  = render 'footer'

app/views/matters/create.html.haml
.matter-create-page

  .matter-create-page__header
    = render 'matters/header'

  .breadcrumb
    - breadcrumb :create_matter
    = breadcrumbs separator: " &rsaquo; "

  %h2 案件依頼の作成が完了しました！

  = link_to root_path do
    .matter-create-page__top-link
      TOPページへ戻る

  .matter-create-page__footer
    = render 'matters/footer'

app/views/matters/edit.html.haml
.matter-edit-page

  .matter-edit-page__header
    = render 'matters/header'

  .breadcrumb
    - breadcrumb :edit_matter
    = breadcrumbs separator: " &rsaquo; "


  .matter-edit-page__title
    案件依頼編集

  .matter-edit-page__form
    = form_for(@matter, url: "/matters/#{@matter.id}", method: :put) do |f|
      = render "devise/shared/error_messages", resource: @matter

      .matter-edit-page__form__title
        .matter-edit-page__form__title__title
          案件名
        .matter-edit-page__form__title__required
          必須
      .matter-edit-page__form__title-form
        = f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "", class: 'title-form'


      .matter-edit-page__form__category
        .matter-edit-page__form__category__title
          案件カテゴリ
        .matter-edit-page__form__category__required
          必須
      .matter-edit-page__form__category-form
        = f.collection_select :matter_category_id, MatterCategory.all, :id, :name, prompt: "カテゴリを選択してください", class: 'category-form'


      .matter-edit-page__form__reward
        .matter-edit-page__form__reward__title
          お支払い金額
        .matter-edit-page__form__reward__required
          必須
      .matter-edit-page__form__reward-form
        = f.text_field :reward, autofocus: true, autocomplete: "reward", placeholder: "半角数字で入力してください", class: 'reward-form'
        円


      .matter-edit-page__form__deadline
        .matter-edit-page__form__deadline__title
          応募受付締切
        .matter-edit-page__form__deadline__required
          必須
      .matter-edit-page__form__deadline-form
        != sprintf(f.date_select(:deadline, prefix:'matter', with_css_classes:'XXXXX', prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:2020, date_separator:'%s'),'年','月')+'日'


      .matter-edit-page__form__prefecture
        .matter-edit-page__form__prefecture__title
          勤務地域(都道府県)
        .matter-edit-page__form__prefecture__required
          必須
      .matter-edit-page__form__prefecture-form
        = f.select :prefecture, Matter.prefectures.keys, {promt: "---"}, class: 'prefecture-form'


      .matter-edit-page__form__start
        .matter-edit-page__form__start__title
          業務開始予定日
        .matter-edit-page__form__start__norequired
          任意
      .matter-edit-page__form__start-form
        != sprintf(f.date_select(:start, prefix:'matter', with_css_classes:'XXXXX', prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:2020, date_separator:'%s'),'年','月')+'日'


      .matter-edit-page__form__end
        .matter-edit-page__form__end__title
          業務終了予定日(希望納品日)
        .matter-edit-page__form__end__required
          必須
      .matter-edit-page__form__end-form
        != sprintf(f.date_select(:end, prefix:'matter', with_css_classes:'XXXXX', prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:2020, date_separator:'%s'),'年','月')+'日'


      .matter-edit-page__form__content
        .matter-edit-page__form__content__title
          業務内容
        .matter-edit-page__form__content__required
          必須
      .matter-edit-page__form__content-form
        = f.text_area :content, autofocus: true, autocomplete: "content", placeholder: "", class: 'content-form'


      .matter-edit-page__form__payment
        .matter-edit-page__form__payment__title
          お支払い方法
        .matter-edit-page__form__payment__norequired
          任意
      .matter-edit-page__form__payment-form
        = f.text_field :payment, autofocus: true, autocomplete: "payment", placeholder: "", class: 'payment-form'


      .matter-edit-page__form__supplement
        .matter-edit-page__form__supplement__title
          補足情報
        .matter-edit-page__form__supplement__norequired
          任意
      .matter-edit-page__form__supplement-form
        = f.text_area :supplement, autofocus: true, autocomplete: "supplement", placeholder: "", class: 'supplement-form'


      .matter-edit-page__form__status
        .matter-edit-page__form__status__title
          公開設定
        .matter-edit-page__form__status__required
          必須
      .matter-edit-page__form__status-form
        = f.select :status, Matter.statuses.keys, {promt: "---"}, class: 'status-form'


      .matter-edit-page__form__actions
        = f.submit "案件依頼を更新する", class: 'submit-button'


  = render 'matters/footer'

app/views/matters/index.html.haml
.top-page

  = render 'header'

  .top-page__search-box
    = render 'search_box'

  = render 'matters_list'

  = render 'footer'

app/views/matters/new.html.haml
.matter-new-page

  .matter-new-page__header
    = render 'matters/header'

  .breadcrumb
    - breadcrumb :new_matter
    = breadcrumbs separator: " &rsaquo; "

  .matter-new-page__title
    案件依頼作成


  .matter-new-page__form
    = form_for(@matter, url: matters_path) do |f|
      = render "devise/shared/error_messages", resource: @matter

      .matter-new-page__form__title
        .matter-new-page__form__title__title
          案件名
        .matter-new-page__form__title__required
          必須
      .matter-new-page__form__title-form
        = f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "" ,class: 'title-form'


      .matter-new-page__form__category
        .matter-new-page__form__category__title
          案件カテゴリ
        .matter-new-page__form__category__required
          必須
      .matter-new-page__form__category-form
        = f.collection_select :matter_category_id, MatterCategory.all, :id, :name, prompt: "カテゴリを選択してください" ,class: 'category-form'


      .matter-new-page__form__reward
        .matter-new-page__form__reward__title
          お支払い金額
        .matter-new-page__form__reward__required
          必須
      .matter-new-page__form__reward-form
        = f.text_field :reward, autocomplete: "reward", placeholder: "半角数字で入力してください" ,class: 'reward-form'
        円


      .matter-new-page__form__deadline
        .matter-new-page__form__deadline__title
          応募受付締切
        .matter-new-page__form__deadline__required
          必須
      .matter-new-page__form__deadline-form
        != sprintf(f.date_select(:deadline, prefix:'matter', with_css_classes:'XXXXX', prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:2020, date_separator:'%s'),'年','月')+'日'


      .matter-new-page__form__prefecture
        .matter-new-page__form__prefecture__title
          勤務地域(都道府県)
        .matter-new-page__form__prefecture__required
          必須
      .matter-new-page__form__prefecture-form
        = f.select :prefecture, Matter.prefectures.keys, {promt: "---"} ,class: 'prefecture-form'


      .matter-new-page__form__start
        .matter-new-page__form__start__title
          業務開始予定日
        .matter-new-page__form__start__norequired
          任意
      .matter-new-page__form__start-form
        != sprintf(f.date_select(:start, prefix:'matter', with_css_classes:'XXXXX', prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:2020, date_separator:'%s'),'年','月')+'日'


      .matter-new-page__form__end
        .matter-new-page__form__end__title
          業務終了予定日(希望納品日)
        .matter-new-page__form__end__required
          必須
      .matter-new-page__form__end-form
        != sprintf(f.date_select(:end, prefix:'matter', with_css_classes:'XXXXX', prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:2020, date_separator:'%s'),'年','月')+'日'


      .matter-new-page__form__content
        .matter-new-page__form__content__title
          業務内容
        .matter-new-page__form__content__required
          必須
      .matter-new-page__form__content-form
        = f.text_area :content, autocomplete: "content", placeholder: "" ,class: 'content-form'


      .matter-new-page__form__payment
        .matter-new-page__form__payment__title
          お支払い方法
        .matter-new-page__form__payment__norequired
          任意
      .matter-new-page__form__payment-form
        = f.text_field :payment, autocomplete: "payment", placeholder: "例）銀行振込、現金でのお支払い" ,class: 'payment-form'


      .matter-new-page__form__supplement
        .matter-new-page__form__supplement__title
          補足情報
        .matter-new-page__form__supplement__norequired
          任意
      .matter-new-page__form__supplement-form
        = f.text_area :supplement, autocomplete: "supplement", placeholder: "" ,class: 'supplement-form'


      .matter-new-page__form__status
        .matter-new-page__form__status__title
          公開設定
        .matter-new-page__form__status__required
          必須
      .matter-new-page__form__status-form
        = f.select :status, Matter.statuses.keys, {promt: "---"} ,class: ''


      .matter-new-page__form__actions
        = f.submit "案件依頼を作成する" ,class: 'submit-button'


  = render 'matters/footer'

app/views/matters/search.html.haml
.search-page
  = render 'header'

  .breadcrumb
    - breadcrumb :search_matters
    = breadcrumbs separator: " &rsaquo; "
  %br

  .search-page__search-box
    = render 'search_box'


  .search-page__matters-list
    %ul
      - @matter_searchs.each do |matter|
        - if matter.deadline > @deadline
          %li.matters-list__content

            .matters-list__content__left
              .matters-list__content__left__title
                = link_to "#{matter.title}", "/matters/#{matter.id}", method: :get, target: blank?
                .matters-list__content__left__title__category
                  = icon('fas', 'fas fa-folder')
                  = matter.matter_category.name

            .matters-list__content__right
              .matters-list__content__right__upper
                %p
                  = icon('fas', 'fas fa-clock')
                  応募受付：
                .matters-list__content__right__upper__deadline
                  = matter.deadline.strftime("%Y年%m月%d日")
                %p
                  まで
              .matters-list__content__right__bottom-line


              .matters-list__content__right__middle
                .matters-list__content__right__middle__reward
                  = icon('fas', 'fas fa-yen-sign')
                  = matter.reward
                .matters-list__content__right__middle__prefecture
                  = icon('fas', 'fas fa-map-marker-alt')
                  就業地域：
                  = matter.prefecture
              .matters-list__content__right__middle__bottom-line


              .matters-list__content__right__lower
                - if matter.start.present?
                  .matters-list__content__right__lower__start
                    = icon('far', 'far fa-calendar-alt')
                    業務開始予定：
                    = matter.start.strftime("%Y年%m月%d日")
                    〜
                .matters-list__content__right__lower__end
                  = icon('far', 'far fa-calendar-alt')
                  業務終了予定(希望納期)：
                  = matter.end.strftime("%Y年%m月%d日")
                .matters-list__content__right__lower__bottom-line
                .matters-list__content__right__lower__musician-name
                  = icon('fas', 'fas fa-user-alt')
                  = link_to "#{matter.musician.name}", "/musicians/#{matter.musician.id}", target: blank?
          %br

  = render 'footer'

app/views/matters/update.html.haml
.matter-update-page

  .matter-update-page__header
    = render 'matters/header'

  .breadcrumb
    - breadcrumb :update_matter
    = breadcrumbs separator: " &rsaquo; "

  %h2 案件依頼内容の更新が完了しました！

  = link_to matter_path do
    .matter-update-page__matter-show-link
      案件依頼内容を確認する


  .matter-update-page__footer
    = render 'matters/footer'