config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }

    devise_scope :user do
      get 'performance', to: 'users/registrations#performance'
      post 'performance', to: 'users/registrations#performance'
      get 'done', to: 'users/registrations#done'
      post 'done', to: 'users/registrations#done'
      get 'edit_user', to: 'users/registrations#edit_user'
      post 'edit_user', to: 'users/registrations#edit_user'
      get 'update_user', to: 'users/registrations#update_user'
      put 'update_user', to: 'users/registrations#update_user'
      get 'logout', to: "users#logout"
    end

    root to: "matters#index"

    resources :users do
      resources :offers, only: [:index, :create, :destroy]
      resources :offered_lists, only: [:index] do
        put 'already_confirmed', to: 'offered_lists#already_confirmed'
        put 'unconfirm', to: 'offered_lists#unconfirm'
      end
    end

    resources :mypages, except: [:destroy]
    resources :applications_lists, only: [:index]
    resources :likes, only: [:index]
    resources :user_chatslists, only: [:index]
    resources :musician_chatslists, only: [:index]

    resources :musicians, except: [:destroy] do
      resources :musician_matterslists, only: [:index]
      resources :tags, only: [:index] do
        collection do
          get 'user_search'
        end
      end
    end


    resources :matters, only: [:new, :create, :show, :edit, :update] do
      resources :likes, only: [:create, :destroy]
      resources :applications, only: [:create, :destroy] do
        resources :applied_users, only: [:index]
      end
      resources :chats, only: [:create] do
        resources :messages, except: [:show] do
          put 'already_read', to: 'messages#already_read'
          put 'unread', to: 'messages#unread'
        end
        resources :reply_messages, except: [:show] do
          put 'already_read', to: 'reply_messages#already_read'
          put 'unread', to: 'reply_messages#unread'
        end
      end
      collection do
        get 'search'
        get 'category_search'
      end
    end



end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :matter
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :musician
  belongs_to :user
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  belongs_to :matter
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :matter
end

app/models/matter.rb
class Matter < ApplicationRecord
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :applications
  has_many :offers
  has_many :chats
  belongs_to :musician
  belongs_to :matter_category

  enum status: {
    公開:0,非公開:1
  }, _prefix: true

  enum prefecture: {
    指定なし:0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
    その他:99
  }, _prefix: true


  def self.search(search)
    if search
      Matter.joins(:musician).where(['title LIKE ? OR content LIKE ? OR name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Matter.all
    end
  end
end

app/models/matter_category.rb
class MatterCategory < ApplicationRecord
  has_many :matters
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/musician.rb
class Musician < ApplicationRecord
  validates :name, :biography, :activity_history, :activity_place, :email ,presence: true
  validates :user_id, uniqueness: true
  has_many :matters
  has_many :chats
  has_many :messages
  belongs_to :user
  has_one :block
  mount_uploader :image, ImageUploader
  # mount_uploader :sound_source, AudioFileUploader
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :user_id, uniqueness: { scope: :matter_id }
  belongs_to :user
  belongs_to :matter
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :users, through: :tags
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  def self.search(search)
    if search
      Tag.where(['skill_id LIKE ?', "%#{search}%"])
    else
      Tag.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, :name_kana, :tel, :birthday, :status ,presence: true
         validates :tel, uniqueness: true
         has_many :likes
         has_many :liked_matters, through: :likes, source: :matter
         has_many :applications
         has_many :offers
         has_many :chats
         has_many :messages
         has_many :tags
         has_many :skills, through: :tags
         has_one :block
         has_one :musician


  enum status: {
    公開:0,非公開:1
  }, _prefix: true

  enum prefecture: {
    指定なし:0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
    その他:99
  }, _prefix: true

  def already_applied?(matter)
    self.applications.exists?(matter_id: matter.id)
  end

  def already_liked?(matter)
    self.likes.exists?(matter_id: matter.id)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_musician, only: [:index, :user_search]

  def index
    
  end

  def user_search
    @user_skill_searchs = Tag.where(skill_id: params[:skill_id])
    @musician_user_id = Musician.find_by(user_id: current_user)
  end


  private

  def set_musician
    @musician = Musician.find(params[:musician_id])
  end

end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/user_search.html.haml
.user-search-page

  .user-search-page__header
    = render 'matters/header'

  .breadcrumb
    - breadcrumb :user_search_tags
    = breadcrumbs separator: " &rsaquo; "
  %br

  .user-search-page__title
    ユーザースキル検索結果


  .user-search-page__search-box
    .user-search-page__search-box__title
      = icon('fas', 'fas fa-search')
      ユーザースキル検索
    .user-search-page__search-box__form
      = form_with(url: user_search_musician_tags_path(@musician), local: true, method: :get, class: "search-form") do |f|
        = f.collection_select :skill_id, Skill.all, :id, :name, prompt: "スキルを選択してください"
        %br
        = f.submit "検索", class: "submit-button"

  %ul.users-list
    - @user_skill_searchs.each do |tag|
      - if tag.user.status == "公開"
        %li.users-list__content

          .users-list__content__name
            .users-list__content__name__title
              = icon('far', 'far fa-user')
              氏名
            .users-list__content__name__text
              = tag.user.name

          .users-list__content__birthday
            .users-list__content__birthday__title
              = icon('fas', 'fas fa-calendar-alt')
              生年月日
            .users-list__content__birthday__text
              = tag.user.birthday.strftime("%Y年%m月%d日")

          .users-list__content__prefecture
            .users-list__content__prefecture__title
              = icon('fas', 'fas fa-map-marker-alt')
              都道府県
            .users-list__content__prefecture__text
              = tag.user.prefecture

          .users-list__content__introduction
            .users-list__content__introduction__title
              = icon('fas', 'fas fa-address-card')
              自己紹介
            .users-list__content__introduction__text
              - if tag.user.introduction.present?
                = safe_join(tag.user.introduction.split("\n"),tag(:br))
              - else
                登録されていません。

          .users-list__content__performance
            .users-list__content__performance__title
              = icon('fas', 'fas fa-file')
              活動実績
            .users-list__content__performance__text
              - if tag.user.performance.present?
                = safe_join(tag.user.performance.split("\n"),tag(:br))
              - else
                登録されていません。

          .users-list__content__portfolio
            .users-list__content__portfolio__title
              = icon('fas', 'fas fa-globe')
              ポートフォリオなどの参考URL
            .users-list__content__portfolio__text
              - if tag.user.portfolio.present?
                %a{ href: "#{tag.user.portfolio}", target: "_blank"} #{tag.user.portfolio}
              - else
                登録されていません。

          .users-list__content__skill
            .users-list__content__skill__title
              = icon('fas', 'fas fa-briefcase')
              スキル
            .users-list__content__skill__text
              - tag.user.tags.each do |tag|
                = tag.skill.name
                |


          .users-list__content__offer
            - if @musician.matters.present?
              = link_to "/users/#{tag.user.id}/offers", method: :get do
                .users-list__content__offer__offer-link
                  このユーザーにオファーを出す
            - else
              .users-list__content__offer__nomatter-message
                ※案件依頼を作成すると、ユーザーにオファーを出すことができます。



  = render 'matters/footer'